// Utility to inject correct Duration metadata into WebM files generated by browser MediaRecorder
// Fixes Chrome / Firefox bug where recorded WebM blobs have missing or infinite duration headers.

export async function fixWebmDuration(blob: Blob, durationMs: number): Promise<Blob> {
  const arrayBuffer = await blob.arrayBuffer();
  const dataView = new DataView(arrayBuffer);
  const bytes = new Uint8Array(arrayBuffer);

  // Look for EBML Segment Info ID: [0x15, 0x49, 0xA9, 0x66]
  let infoOffset = -1;
  for (let i = 0; i < bytes.length - 4; i++) {
    if (
      bytes[i] === 0x15 &&
      bytes[i + 1] === 0x49 &&
      bytes[i + 2] === 0xa9 &&
      bytes[i + 3] === 0x66
    ) {
      infoOffset = i;
      break;
    }
  }

  if (infoOffset === -1) {
    // If not found, return original blob
    return blob;
  }

  // Look for Duration ID: [0x44, 0x89] inside Info header
  let durationOffset = -1;
  for (let i = infoOffset; i < Math.min(infoOffset + 250, bytes.length - 6); i++) {
    if (bytes[i] === 0x44 && bytes[i + 1] === 0x89) {
      durationOffset = i;
      break;
    }
  }

  if (durationOffset !== -1) {
    // Check if 4-byte or 8-byte float
    const size = bytes[durationOffset + 2];
    if (size === 0x84) {
      // 4-byte float (float32)
      dataView.setFloat32(durationOffset + 3, durationMs, false);
      return new Blob([arrayBuffer], { type: blob.type });
    } else if (size === 0x88) {
      // 8-byte float (float64)
      dataView.setFloat64(durationOffset + 3, durationMs, false);
      return new Blob([arrayBuffer], { type: blob.type });
    }
  }

  return blob;
}

export function createStandaloneHtmlPresentation(
  mode: 'tutorial' | 'pitch',
  scenes: Array<{
    stepNumber: number;
    title: string;
    badge: string;
    startSec: number;
    endSec: number;
    instructionTitle: string;
    instructionText: string;
    narration: string;
  }>
): string {
  const duration = scenes[scenes.length - 1].endSec;
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SkillSpire AI - ${mode === 'tutorial' ? 'Website Tutorial & Instruction Video' : 'Official Competition Demo'}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    body { background: #030712; color: #f8fafc; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; }
    .container { width: 100%; max-width: 1100px; background: #0b1329; border: 1px solid #3b82f644; border-radius: 20px; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.7); }
    .header { background: linear-gradient(90deg, #0f172a, #1e1b4b); padding: 16px 24px; border-bottom: 1px solid #1e293b; display: flex; justify-content: space-between; align-items: center; }
    .header h1 { font-size: 1.1rem; font-weight: 800; color: #fff; display: flex; align-items: center; gap: 8px; }
    .badge { background: #2563eb; color: #fff; font-size: 0.7rem; font-weight: 800; padding: 2px 8px; border-radius: 9999px; text-transform: uppercase; }
    .canvas-box { position: relative; width: 100%; aspect-ratio: 16/9; background: #000; }
    canvas { width: 100%; height: 100%; display: block; }
    .controls { padding: 16px 24px; background: #0f172a; border-top: 1px solid #1e293b; display: flex; flex-direction: column; gap: 12px; }
    .progress-bar-container { width: 100%; height: 8px; background: #1e293b; border-radius: 4px; cursor: pointer; position: relative; overflow: hidden; }
    .progress-bar { height: 100%; background: linear-gradient(90deg, #3b82f6, #8b5cf6); width: 0%; transition: width 0.1s linear; }
    .buttons-row { display: flex; justify-content: space-between; align-items: center; }
    .btn { background: #2563eb; color: #fff; border: none; padding: 8px 16px; border-radius: 8px; font-weight: 700; font-size: 0.85rem; cursor: pointer; transition: background 0.2s; }
    .btn:hover { background: #1d4ed8; }
    .time-display { font-family: monospace; font-size: 0.9rem; color: #94a3b8; font-weight: bold; }
    .chapters { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 8px; margin-top: 8px; }
    .chapter-btn { background: #1e293b; color: #cbd5e1; border: 1px solid #334155; padding: 6px 10px; border-radius: 6px; font-size: 0.75rem; text-align: left; cursor: pointer; }
    .chapter-btn.active { border-color: #3b82f6; background: #1e3a8a; color: #fff; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>SkillSpire AI <span class="badge">${mode === 'tutorial' ? '3-Minute Master Walkthrough (180s)' : 'Official Competition Demo'}</span></h1>
      <span style="font-size: 0.8rem; color: #94a3b8;">Offline Standalone Edition</span>
    </div>
    <div class="canvas-box">
      <canvas id="playerCanvas" width="1280" height="720"></canvas>
    </div>
    <div class="controls">
      <div class="progress-bar-container" id="progressBarContainer">
        <div class="progress-bar" id="progressBar"></div>
      </div>
      <div class="buttons-row">
        <div style="display: flex; gap: 8px; align-items: center;">
          <button class="btn" id="playBtn">▶ Play</button>
          <button class="btn" id="voiceBtn" style="background: #334155;">🔊 Voice: ON</button>
          <span class="time-display" id="timeDisplay">00:00 / ${Math.floor(duration/60).toString().padStart(2,'0')}:${(duration%60).toString().padStart(2,'0')}</span>
        </div>
        <button class="btn" id="fsBtn" style="background: #334155;">⛶ Fullscreen</button>
      </div>
      <div class="chapters" id="chaptersContainer"></div>
    </div>
  </div>

  <script>
    const scenes = ${JSON.stringify(scenes)};
    const totalDuration = ${duration};
    let currentTime = 0;
    let isPlaying = false;
    let isVoiceOn = true;
    let lastTime = Date.now();
    let currentSceneId = 1;

    const canvas = document.getElementById('playerCanvas');
    const ctx = canvas.getContext('2d');
    const playBtn = document.getElementById('playBtn');
    const voiceBtn = document.getElementById('voiceBtn');
    const timeDisplay = document.getElementById('timeDisplay');
    const progressBar = document.getElementById('progressBar');
    const progressBarContainer = document.getElementById('progressBarContainer');
    const chaptersContainer = document.getElementById('chaptersContainer');

    scenes.forEach(s => {
      const b = document.createElement('button');
      b.className = 'chapter-btn' + (s.id === 1 ? ' active' : '');
      b.id = 'chap-' + s.id;
      b.textContent = s.stepNumber + '. ' + s.title;
      b.onclick = () => seek(s.startSec);
      chaptersContainer.appendChild(b);
    });

    function speak(text) {
      if (!isVoiceOn || !('speechSynthesis' in window)) return;
      window.speechSynthesis.cancel();
      const u = new SpeechSynthesisUtterance(text);
      u.rate = 0.95;
      window.speechSynthesis.speak(u);
    }

    function formatTime(s) {
      const m = Math.floor(s / 60);
      const sec = Math.floor(s % 60);
      return (m < 10 ? '0' : '') + m + ':' + (sec < 10 ? '0' : '') + sec;
    }

    function seek(t) {
      currentTime = Math.max(0, Math.min(totalDuration, t));
      const s = scenes.find(x => currentTime >= x.startSec && currentTime < x.endSec) || scenes[0];
      currentSceneId = s.id;
      updateUI();
      if (isPlaying) speak(s.narration);
    }

    function render(t) {
      const w = 1280, h = 720;
      const grad = ctx.createLinearGradient(0, 0, w, h);
      grad.addColorStop(0, '#030712');
      grad.addColorStop(0.5, '#0f172a');
      grad.addColorStop(1, '#1e1b4b');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, w, h);

      // Top Simulated Browser
      ctx.fillStyle = '#0b1329';
      ctx.fillRect(40, 25, w - 80, 45);
      ctx.fillStyle = '#ef4444'; ctx.beginPath(); ctx.arc(65, 47, 5, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = '#f59e0b'; ctx.beginPath(); ctx.arc(80, 47, 5, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = '#10b981'; ctx.beginPath(); ctx.arc(95, 47, 5, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = '#38bdf8'; ctx.font = 'bold 12px monospace'; ctx.fillText('🔒 https://skillspire.ai/app/tutorial', 120, 52);

      const scene = scenes.find(x => t >= x.startSec && t < x.endSec) || scenes[scenes.length - 1];

      // Scene Card
      ctx.fillStyle = '#0f172a';
      ctx.beginPath();
      ctx.roundRect(60, 95, w - 120, 520, 16);
      ctx.fill();
      ctx.strokeStyle = '#3b82f644';
      ctx.stroke();

      // Badge
      ctx.fillStyle = '#2563eb';
      ctx.beginPath();
      ctx.roundRect(90, 125, 200, 30, 8);
      ctx.fill();
      ctx.fillStyle = '#fff';
      ctx.font = 'bold 12px monospace';
      ctx.fillText(scene.badge, 105, 145);

      // Title & Text
      ctx.fillStyle = '#fff';
      ctx.font = 'bold 28px system-ui';
      ctx.fillText(scene.title, 90, 195);

      ctx.fillStyle = '#38bdf8';
      ctx.font = 'bold 18px system-ui';
      ctx.fillText(scene.instructionTitle, 90, 235);

      ctx.fillStyle = '#cbd5e1';
      ctx.font = '16px system-ui';
      ctx.fillText(scene.instructionText, 90, 275);

      // Bottom CC Subtitles
      ctx.fillStyle = 'rgba(0, 0, 0, 0.85)';
      ctx.beginPath();
      ctx.roundRect(100, h - 70, w - 200, 50, 12);
      ctx.fill();
      ctx.fillStyle = '#f8fafc';
      ctx.font = '16px system-ui';
      ctx.textAlign = 'center';
      ctx.fillText('"' + scene.narration + '"', w / 2, h - 38);
      ctx.textAlign = 'left';
    }

    function updateUI() {
      timeDisplay.textContent = formatTime(currentTime) + ' / ' + formatTime(totalDuration);
      progressBar.style.width = (currentTime / totalDuration * 100) + '%';
      scenes.forEach(s => {
        const el = document.getElementById('chap-' + s.id);
        if (el) {
          if (currentTime >= s.startSec && currentTime < s.endSec) {
            el.className = 'chapter-btn active';
          } else {
            el.className = 'chapter-btn';
          }
        }
      });
      render(currentTime);
    }

    function tick() {
      if (!isPlaying) return;
      const now = Date.now();
      const delta = (now - lastTime) / 1000;
      lastTime = now;
      currentTime += delta;
      if (currentTime >= totalDuration) {
        currentTime = totalDuration;
        isPlaying = false;
        playBtn.textContent = '▶ Play';
        window.speechSynthesis.cancel();
      } else {
        const s = scenes.find(x => currentTime >= x.startSec && currentTime < x.endSec) || scenes[0];
        if (s.id !== currentSceneId) {
          currentSceneId = s.id;
          speak(s.narration);
        }
        requestAnimationFrame(tick);
      }
      updateUI();
    }

    playBtn.onclick = () => {
      if (currentTime >= totalDuration) currentTime = 0;
      isPlaying = !isPlaying;
      playBtn.textContent = isPlaying ? '⏸ Pause' : '▶ Play';
      lastTime = Date.now();
      if (isPlaying) {
        const s = scenes.find(x => currentTime >= x.startSec && currentTime < x.endSec) || scenes[0];
        speak(s.narration);
        tick();
      } else {
        window.speechSynthesis.cancel();
      }
    };

    voiceBtn.onclick = () => {
      isVoiceOn = !isVoiceOn;
      voiceBtn.textContent = isVoiceOn ? '🔊 Voice: ON' : '🔇 Voice: OFF';
      if (!isVoiceOn) window.speechSynthesis.cancel();
    };

    progressBarContainer.onclick = (e) => {
      const rect = progressBarContainer.getBoundingClientRect();
      const clickRatio = (e.clientX - rect.left) / rect.width;
      seek(clickRatio * totalDuration);
    };

    document.getElementById('fsBtn').onclick = () => {
      if (!document.fullscreenElement) {
        document.documentElement.requestFullscreen();
      } else {
        document.exitFullscreen();
      }
    };

    updateUI();
  </script>
</body>
</html>`;
}
