import React, { useState } from 'react';
import { X, Download, Copy, Check, Printer, FileText, Sparkles } from 'lucide-react';
import { AnalysisResult, UserProgressState } from '../types';

interface ExportModalProps {
  analysisResult: AnalysisResult;
  progress: UserProgressState;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  analysisResult,
  progress,
  onClose
}) => {
  const [copied, setCopied] = useState(false);
  const profile = analysisResult.userProfile;
  const career = analysisResult.primaryCareer;

  const generateMarkdown = () => {
    return `# SkillSpire AI — Personalized Career Strategy Brief
**Candidate:** ${profile.fullName}
**Generated Date:** ${new Date(analysisResult.generatedAt).toLocaleDateString()}
**Target Career:** ${career.career.title} (${career.matchScore}% Match Score)
**Estimated Timeline:** ${career.estimatedMonths} @ ${profile.weeklyLearningTime}/week

---

## 1. Executive Career Fit & Explainable AI Summary
${analysisResult.aiExplanation.fitSummary}

### Why This Career Fits You:
${analysisResult.aiExplanation.whyThisCareerFits}

### Recommendation Logic:
${analysisResult.aiExplanation.recommendationLogic}

---

## 2. Existing Strengths
${analysisResult.topStrengths.map(s => `- [x] **${s}** (Demonstrated Asset)`).join('\n')}

---

## 3. Prioritized Skill Gap Breakdown
${analysisResult.allSkillGaps.map(g => `- **${g.skillName}**: Current: ${g.currentLevel} → Required: ${g.requiredLevel} [Gap Severity: **${g.gapSeverity}** | Priority ${g.priorityOrder}]`).join('\n')}

---

## 4. Personalized 5-Phase Learning Roadmap
${analysisResult.roadmap.map(p => `### Phase ${p.phaseNumber}: ${p.title} (${p.durationWeeks} Weeks)
*Focus:* ${p.focusArea}
**Key Objectives:**
${p.objectives.map(o => `  * ${o}`).join('\n')}
**Milestones:**
${p.milestones.map(m => `  - [ ] **${m.title}**: ${m.deliverable}`).join('\n')}
`).join('\n')}

---

## 5. Recommended High-Impact Portfolio Projects
${analysisResult.allRecommendedProjects.map(proj => `### ${proj.title}
*Difficulty:* ${proj.difficulty} | *Est. Time:* ${proj.estimatedWeeks} weeks | *Portfolio Value Score:* ${proj.portfolioValueScore}/100
${proj.description}
**Tech Stack:** ${proj.suggestedTechStack.join(', ')}
**Why Recommended:** ${proj.whyRecommended}
`).join('\n')}

---

## 6. Actionable Strategy Tips
${analysisResult.aiExplanation.tailoredStrategyTips.map(t => `- ${t}`).join('\n')}

*Generated by SkillSpire AI — "Your skills today. Your career tomorrow."*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(analysisResult, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `SkillSpire-Career-Strategy-${profile.fullName.replace(/\s+/g, '-')}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div className="bg-white w-full max-w-3xl rounded-2xl border border-slate-200 shadow-2xl overflow-hidden my-auto animate-in fade-in zoom-in-95 duration-200 max-h-[90vh] flex flex-col">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center font-bold">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">Career Strategy Brief Export</h2>
              <p className="text-xs text-slate-500">Download, copy, or print your complete diagnostic roadmap</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-200"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Preview Box */}
        <div className="p-6 overflow-y-auto space-y-4 font-mono text-xs text-slate-700 bg-slate-50/70 border-b border-slate-200">
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs whitespace-pre-wrap font-sans text-xs leading-relaxed max-h-96 overflow-y-auto">
            {generateMarkdown()}
          </div>
        </div>

        {/* Actions */}
        <div className="p-4 bg-white flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-3.5 py-2 text-xs font-semibold rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Markdown!' : 'Copy Markdown'}</span>
            </button>
            <button
              onClick={handleDownloadJSON}
              className="px-3.5 py-2 text-xs font-semibold rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 flex items-center gap-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export JSON</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-3.5 py-2 text-xs font-semibold rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 flex items-center gap-1.5 transition-colors hidden sm:flex"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Brief</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold shadow-xs"
          >
            Done
          </button>
        </div>

      </div>
    </div>
  );
};
